export const styles = {
  wrapper: (theme) => ({
    display: 'flex',
    // flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: theme.spacing(4),
  }),
  specialisation_left_box: {
    display: 'flex',
    flexDirection: 'column',
  },
  specialisation_right_box: (theme) => ({
    minWidth: '890px',
    display: 'flex',
    justifyContent: 'left',
    gap: theme.spacing(4),
  }),
  specialisation_title: (theme) => ({
    marginBottom: theme.spacing(5),
    fontSize: 34,
  }),
  make_main_btn: (theme) => ({
    color: theme.palette.action.active,
    borderColor: theme.palette.action.active,
    minWidth: '216px',
    padding: '12px 16px',
    textTransform: 'none',
    '&:hover': {
      color: theme.palette.primary[500],
    },
  }),
  add_specialisation_btn: (theme) => ({
    width: '134px',
    height: '134px',
    backgroundColor: theme.palette.neutral[600],
    borderRadius: theme.spacing(2),
  }),

  figure: {
    display: 'flex',
    height: '138px',
    width: '228px',
    borderRadius: '10px',
    position: 'relative',
    '&::before': {
      content: '""',
      display: 'flex',
      position: 'absolute',
      borderBottom: '1px solid #FF0000',
      borderLeft: '1px solid #FF0000',
      borderRight: '1px solid #FF0000',
      // backgroundColor: 'red',
      top: 90,
      left: 0,
      height: 45,
      width: 'calc(100% - 45px)',
      borderRadius: '0 0 10px 10px',
    },
    '&::after': {
      content: '""',
      display: 'flex',
      position: 'absolute',
      borderTop: '1px solid #FF0000',
      borderLeft: '1px solid #FF0000',
      borderRight: '1px solid #FF0000',
      // backgroundColor: 'red',
      top: 0,
      left: 0,
      height: 'calc(100% - 45px)',
      width: '100%',
      borderRadius: '10px 10px 10px 0',
    },
  },
  figure_deco: {
    position: 'absolute',
    // backgroundColor: 'red',
    height: 40,
    width: 40,
    top: 95,
    right: 0,
    borderRadius: '10px',
    '&::before': {
      content: '""',
      display: 'flex',
      position: 'absolute',
      top: -5,
      left: -5,
      height: '100%',
      width: '100%',
      // backgroundColor: 'white',
      borderBottomRightRadius: '10px',
      borderTop: '1px solid #FF0000',
    },
  }

}