export const styles = {
  wrapper: (theme) => ({
    display: 'flex',
    // flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: theme.spacing(4),
  }),
  specialisation_left_box: {
    display: 'flex',
    flexDirection: 'column',
  },
  specialisation_right_box: (theme) => ({
    minWidth: '890px',
    display: 'flex',
    justifyContent: 'left',
    gap: theme.spacing(4),
  }),
  page_title: (theme) => ({
    marginBottom: theme.spacing(5),
    fontSize: 34,
  }),
  make_main_btn: (theme) => ({
    color: theme.palette.action.active,
    borderColor: theme.palette.action.active,
    minWidth: '216px',
    padding: '12px 16px',
    textTransform: 'none',
    '&:hover': {
      color: theme.palette.primary[500],
    },
  }),
  add_specialisation_btn: (theme) => ({
    width: '134px',
    height: '134px',
    backgroundColor: theme.palette.neutral[600],
    borderRadius: theme.spacing(2),
  }),

  figure: (theme) => ({
    display: 'flex',
    flexDirection: 'column',
    height: '138px',
    width: '228px',
    borderRadius: '10px',
    position: 'relative',
    backgroundColor: theme.palette.neutral[600],
    '&::before': {
      content: '""',
      display: 'flex',
      position: 'absolute',
      // borderBottom: '1px solid #FF0000',
      // borderLeft: '1px solid #FF0000',
      // borderRight: '1px solid #FF0000',
      // backgroundColor: '#3E3E40',
      top: 90,
      left: 0,
      height: 45,
      width: 'calc(100% - 45px)',
      borderRadius: '0 0 10px 10px',
    },
    '&::after': {
      content: '""',
      display: 'flex',
      position: 'absolute',
      // borderTop: '1px solid #FF0000',
      // borderLeft: '1px solid #FF0000',
      // borderRight: '1px solid #FF0000',
      // backgroundColor: 'red',
      top: 0,
      left: 0,
      height: 'calc(100% - 45px)',
      width: '100%',
      borderRadius: '10px 10px 10px 0',
    },
  }),
  figure_deco: {
    position: 'absolute',
    // backgroundColor: 'red',
    height: 43,
    width: 47,
    top: 95,
    right: 0,
    borderRadius: '10px',
    '&::before': {
      content: '""',
      display: 'flex',
      position: 'absolute',
      top: 0,
      left: 0,
      height: '100%',
      width: '100%',
      backgroundColor: '#303032',
      borderTopLeftRadius: '10px',
      borderBottomRightRadius: '10px',
      // borderTop: '1px solid #FF0000',
      // borderLeft: '1px solid #FF0000',
    },
  },
  specialisation_title: (theme) => ({
    display: 'flex',
    flexDirection: 'column',
    marginTop: theme.spacing(2),
    marginLeft: theme.spacing(3),
    marginRight: theme.spacing(5),
    marginBottom: theme.spacing(3),
  }),
  hardAndSoftSkills: (theme) => ({
    marginLeft: theme.spacing(3),
    display: 'flex',
    flexDirection: 'row',
  }),
  softSkills: (theme) => ({
    display: 'flex',
    flexDirection: 'column',
    marginRight: theme.spacing(3),
  }),
  hardSkills: {
    display: 'flex',
    flexDirection: 'column',
  },
  skillsStatistic: {
    lineHeight: '18px',
    letterSpacing: '0.16px',
    fontSize: '11px'
  },
  editSpecialisation_btn: (theme) => ({
    marginLeft: '8px',
    marginTop: '7px',
    zIndex: 1,
    border: '1px solid #444446',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '7px',
    boxSizing: 'content-box',
    color: theme.palette.text.secondary,
  })

}