import InterviewSoftSkillsSinglePassedInterview from '@components/PageComponents/SinglePassedInterviewComponents/InterviewSoftSkillsSinglePassedInterview/InterviewSoftSkillsSinglePassedInterview';

export default InterviewSoftSkillsSinglePassedInterview;
