export const modalNames = {
  achievementModal: 'achievementModal',
  achievementEditModal: 'achievementEditModal',
  workExperienceModal: 'workExperienceModal',
  workExperienceEditModal: 'workExperienceEditModal',
  educationModal: 'educationModal',
  educationEditModal: 'educationEditModal',
  userInfoModal: 'userInfoModal',
  loginModal: 'loginModal',
  feedbackProjectModal: 'feedbackProjectModal',
  specializationModal: 'specializationModal',
  specializationEditModal: 'specializationEditModal',
  hardSkillsModal: 'hardSkillsModal',
  softSkillsModal: 'softSkillsModal',
  scheduleInterviewModal: 'scheduleInterviewModal',
  feedbackInterviewModal: 'feedbackInterviewModal',
  registrationModal: 'registrationModal',
  checkEmailModal: 'checkEmailModal',
  resetPasswordModal: 'resetPasswordModal',
  confirmationModal: 'ConfirmationModal',
  confirmDeleteSpecialization: 'confirmDeleteSpecialization',
};
