export const TAG_TYPES = {
  Specialization: 'Specialization',
  Masteries: 'Masteries',
  MainMastery: 'MainMastery',
  HardSkills: 'HardSkills',
  SoftSkills: 'SoftSkills',
  PersonalUser: 'PersonalUser',
  DefLanguage: 'DefLanguage',
  Achievement: 'Achievement',
  Education: 'Education',
  Feedback: 'Feedback',
  Notifications: 'Notifications',
  Skills: 'Skills',
  Event: 'Event',
  DefSpecializations: 'DefSpecializations',
  AvatarUser: 'AvatarUser',
  ContactList: 'ContactList',
  LanguageUser: 'LanguageUser',
  WorkExperience: 'WorkExperience',
  Chat: 'Chat',
  ChatHistory: 'ChatHistory',
  InterviewRequest: 'InterviewRequest',
  InterviewRequestByMasteryId: 'InterviewRequestByMasteryId',
  ScheduledInterview: 'ScheduledInterview',
  PassedInterview: 'PassedInterview',
  ServiceWorkerNotification: 'ServiceWorkerNotification',
};

export const TAG_TYPES_ARRAY = Object.values(TAG_TYPES);
