import TelegramNotificationsSkeleton from '@components/UI/Skeleton/Pages/settingsSkeleton/notificationSkeleton/TelegramNotificationsSkeleton/TelegramNotificationsSkeleton';

export default TelegramNotificationsSkeleton;
