export const SOCIAL_TYPES = {
  EMAIL: 'EMAIL',
  PHONE_NUMBER: 'PHONE_NUMBER',
  TELEGRAM_LINK: 'TELEGRAM_LINK',
  LINKEDIN_LINK: 'LINKEDIN_LINK',
  GITHUB_LINK: 'GITHUB_LINK',
  BEHANCE_LINK: 'BEHANCE_LINK',
};
