const defaultHardSkills = {
  ['Front-End Engineer']: ['HTML', 'CSS', 'Java Script'],
  ['Project Manager']: ['Jira', 'Confluence', 'Project Management'],
  ['Internet Marketing Specialist']: ['Google Ads', 'Google Analytics'],
  ['JavaScript Engineer']: ['JavaScript'],
  ['Node.js Engineer']: ['Node.js', 'JavaScript'],
  ['Java Engineer']: ['OOP', 'Java', 'Maven / Gradle'],
  ['PHP Engineer']: ['PHP', 'composer'],
  ['C# Engineer']: ['OOP', '.Net / .Net Core', 'ASP.NET Core', 'LINQ'],
  ['Social Media Marketing (SMM) Specialist']: ['Facebook Ads Manager'],
  ['Python Engineer']: ['Python'],
  ['QA Engineer']: ['UI Testing', 'API Testing', 'Test Documentation', 'Jira'],
  ['UI/UX Designer']: ['Figma', 'UX research', 'UI design', 'Guidelines'],
  ['Scrum Master']: ['Jira', 'Scrum Guide'],
  ['AI/ML Engineer']: ['Python', 'Machine Learning Algorithms'],
  ['DevOps Engineer']: ['Docker', 'Kubernetes'],
  ['C++ Engineer']: ['C++'],
  ['Android Engineer']: ['Android Studio', 'Kotlin'],
  ['Kotlin Engineer']: ['Kotlin', 'Android Studio', 'Jetpack'],
  ['HR Specialist']: ['Google Sheets / Excel', 'ATS'],
  ['Designer']: ['Adobe Creative Suite', 'Figma', 'Affinity Designer'],
  ['Sales Specialist']: ['HubSpot / Salesforce', 'Lemlist / Apollo', 'Google Sheets'],
  ['Marketing Specialist']: ['Creativity', 'Analytical skills', 'Marketing plan & strategy'],
  ['Data Analyst']: ['SQL', 'Excel', 'Tableau / Power BI'],
  ['iOS/macOS Engineer']: ['Swift', 'Core Data'],
  ['Golang Engineer']: ['Go'],
  ['Database Engineer']: ['SQL', 'ERD'],
};

export default defaultHardSkills;
