export const styles = {
  popup: (theme) => ({
    width: '413px',
    height: '200px',
    padding: '18px',
    paddingTop: '36px',
    position: 'absolute',
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'column',
    backgroundColor: theme.palette.schedule.popup.backgroundColor,
    boxShadow: theme.palette.schedule.popup.boxShadow,
    zIndex: 1000,
  }),
  popupTriangularBottomLeft: (theme) => ({
    position: 'absolute',
    bottom: '0px',
    left: '-19px',
    width: 0,
    height: 0,
    borderLeft: '9px solid transparent',
    borderRight: `14px solid ${theme.palette.schedule.popup.popupBorderColor}`,
    borderTop: '10px solid transparent',
    zIndex: 1001,
  }),
  popupTriangularTopLeft: (theme) => ({
    position: 'absolute',
    bottom: '190px',
    left: '-19px',
    width: 0,
    height: 0,
    borderLeft: '9px solid transparent',
    borderRight: `14px solid ${theme.palette.schedule.popup.popupBorderColor}`,
    borderBottom: '10px solid transparent',
    zIndex: 1001,
  }),
  popupTriangularTopRight: (theme) => ({
    position: 'absolute',
    bottom: '190px',
    right: '-19px',
    width: 0,
    height: 0,
    borderRight: '9px solid transparent',
    borderLeft: `14px solid ${theme.palette.schedule.popup.popupBorderColor}`,
    borderBottom: '10px solid transparent',
    zIndex: 1001,
  }),
  popupTriangularBottomRight: (theme) => ({
    position: 'absolute',
    bottom: '0px',
    right: '-19px',
    width: 0,
    height: 0,
    borderRight: '9px solid transparent',
    borderLeft: `14px solid ${theme.palette.schedule.popup.popupBorderColor}`,
    borderTop: '10px solid transparent',
    zIndex: 1001,
  }),
  closeIcon: (theme) => ({
    position: 'absolute',
    right: 0,
    top: 0,
    color: theme.palette.schedule.popup.closeIconColor,
  }),
  modalTitle: {
    position: 'absolute',
    left: '16px',
    top: '16px',
    fontSize: '16px',
  },
  infoContainer: (theme) => ({
    display: 'flex',
    paddingTop: '12px',
    marginBottom: theme.spacing(2),
  }),
  userInfo: (theme) => ({
    width: '45%',
    display: 'flex',
    flexDirection: 'column',
    paddingRight: theme.spacing(4),
    borderRight: `1px dashed ${theme.palette.schedule.popup.userInfoBorderColor}`,
  }),
  interviewerInfo: (theme) => ({
    width: '55%',
    display: 'flex',
    flexDirection: 'column',
    paddingLeft: theme.spacing(4),
  }),
  title: (theme) => ({
    color: theme.palette.schedule.popup.titleColor,
    margin: 0,
    marginBottom: theme.spacing(2),
  }),
  name: (theme) => ({
    color: theme.palette.schedule.userLinksEvent.color,
    margin: theme.spacing(0),
    marginBottom: theme.spacing(2),
    '&:hover': {
      color: theme.palette.schedule.userLinksEvent.hover.color,
    },
    '&:active': {
      color: theme.palette.schedule.userLinksEvent.active.color,
    },
  }),
  position: (theme) => ({
    margin: 0,
    marginBottom: theme.spacing(2),
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  }),
  role: {
    margin: 0,
    textTransform: 'capitalize',
  },
  buttonsContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  icon: (theme) => ({
    color: theme.palette.schedule.userLinksEvent.color,
    display: 'block',
    textTransform: 'none',
    padding: 0,

    '&:hover': {
      color: theme.palette.schedule.userLinksEvent.hover.color,
    },
    '&:active': {
      color: theme.palette.schedule.userLinksEvent.active.color,
    },
  }),
  outlined: (theme) => ({
    display: 'block',
    height: '100%',
    border: 'none',
    color: theme.palette.schedule.popup.iconColor,
    fontSize: '14px',
    textTransform: 'none',
    padding: 0,
    width: '150px',
  }),
};
