import PreviewVideoPassedInterview from '@components/PageComponents/SinglePassedInterviewComponents/PreviewVideoPassedInterview/PreviewVideoPassedInterview';

export default PreviewVideoPassedInterview;
