import InterviewHardSkillsSinglePassedInterview from '@components/PageComponents/SinglePassedInterviewComponents/InterviewHardSkillsSinglePassedInterview/InterviewHardSkillsSinglePassedInterview';

export default InterviewHardSkillsSinglePassedInterview;
