export const styles = {
  contained: (theme) => ({
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '16px',
    color: theme.palette.text.primary,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginY: 0,
    paddingY: 20,
    paddingX: 12,
    width: '100%',
    backgroundColor: theme.palette.primary.main,
    '&:hover': {
      backgroundColor: theme.palette.primary.dark,
    },
    '&:disabled': {
      backgroundColor: theme.palette.action.disabledBackground,
      color: '#FFFFFF80',
    },
  }),
  text: (theme) => ({
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '24px',
    color: theme.palette.text.secondary,
    textAlign: 'center',
    textTransform: 'capitalize',
    marginY: 0,
    paddingY: 0,
    paddingX: 0,
    width: 'auto',
    backgroundColor: 'transparent',
    '&:hover': {
      backgroundColor: 'transparent',
    },
  }),
  outlined: (theme) => ({
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '24px',
    color: theme.palette.text.primary,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginY: 0,
    paddingY: 20,
    paddingX: 12,
    width: '100%',
    backgroundColor: 'transparent',
    '&:hover': {
      backgroundColor: 'transparent',
    },
  }),
};
