export default {
  home: '/',
  profile: '/profile',
  schedule: '/schedule',
  specializations: '/specializations',
  interviews: '/interviews',
  scheduledInterviews: '/interviews/scheduled',
  passedInterviews: '/interviews/passed',
  interviewRequests: '/interviews/requests',
  generalSettings: '/settings/general',
  notificationsSettings: '/settings/notifications',
  bookmark: '/bookmark',
  faq: '/faq',
  privacy_policy: '/privacy_policy',
  terms_and_conditions: '/terms_and_conditions',
  error_404: '/ErrorPage',
};
