import UserCardSinglePassedInterview from '@components/PageComponents/SinglePassedInterviewComponents/UserCardSinglePassedInterview/UserCardSinglePassedInterview';

export default UserCardSinglePassedInterview;
