import EmptyStatisticsPassedInterview from '@components/PageComponents/SinglePassedInterviewComponents/EmptyStatisticsPassedInterview/EmptyStatisticsPassedInterview';

export default EmptyStatisticsPassedInterview;
