export const styles = {
  position: (theme) => ({
    position: 'fixed',
    top: 'calc(100% - 684px)',
    left: 'calc(100% - 580px)',
    zIndex: 1500,
    boxShadow: `0 5px 5px -3px rgba(0,0,0,0.2),0 8px 10px 1px rgba(0,0,0,0.14),0 3px 14px 2px rgba(0,0,0,0.12)`,
    border: `1px solid ${theme.palette.chatForm.borderColor}`,
    height: '100%',
    maxHeight: '683px',
    backgroundColor: theme.palette.chatForm.backgroundColor,
    borderRadius: 1,
  }),
  resizeHandle: {
    position: 'absolute',
    width: '5px',
    height: '100%',
    backgroundColor: 'transparent',
    top: 0,
    right: -5,
    cursor: 'ew-resize',
    zIndex: 10,
  },
  container: {
    maxHeight: '683px',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  chatWrapper: (theme) => ({
    flex: '1 1 100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: theme.palette.chatForm.chatWrapper.backgroundColor,
    padding: '16px 16px 0 16px',
    maxHeight: '100%',
    height: '100%',
    overflowX: 'hidden',
    overflowY: 'auto',
    '&::-webkit-scrollbar': {
      width: 10,
    },
    '&::-webkit-scrollbar-track': {
      backgroundColor: theme.palette.scroll.scrollWrapp.backgroundColor,
      borderRadius: 0,
    },
    '&::-webkit-scrollbar-thumb': {
      borderRadius: 6,
      backgroundColor: theme.palette.scroll.scrollEl.backgroundColor,
    },
  }),
};
