export const styles = {
  skillsWrapper: {
    width: '100%',
    height: 260,
    padding: 24,
  },
  skillsTitle: {
    marginBottom: 8,
    fontSize: 20,
    lineHeight: 1.6,
    fontWeight: 500,
    color: '#FFFFFF',
  },
  hardSkills: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  skillsText: {
    marginRight: 10,
    color: '#C5C5C6',
    fontSize: 20,
    lineHeight: 1.6,
  },
  skillsRating: {
    color: '#C5C5C6',
    fontSize: 16,
    lineHeight: 1.75,
  },
  softSkills: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 28,
    color: '#C5C5C6',
    fontSize: 20,
    lineHeight: 1.6,
  },
  interviewHistory: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
  },
  doneInterviewsQuantity: {
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 1.6,
  },
  doneInterviews: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: 72,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    padding: 12,
    paddingTop: 12,
    color: '#16FFB9',
    border: 1,
    borderColor: '#16FFB9',
    borderRadius: 1,
    fontSize: 21,
    lineHeight: 1,
  },
  completedInterviewsQuantity: {
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 1.6,
  },
  completedInterviews: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: 72,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    paddingTop: 12,
    color: '#25CBFF',
    borderColor: '#25CBFF',
    border: 1,
    borderRadius: 1,
    fontSize: 12,
    lineHeight: 1,
  },
};
