import { action } from '@storybook/addon-actions';
import { decorators } from '../../../../.storybook/preview';
import FormSelect from './FormSelect';

const userCountries = [
  'Albania',
  'Andorra',
  'Argentina',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Bosnia And Herzegovina',
  'Brazil',
  'Bulgaria',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Malta',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'San Marino',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Trinidad And Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Liechtenstein',
];

export default {
  title: 'Form/Select/FormSelect',
  component: FormSelect,
  parameters: {
    layout: 'centered',
    backgrounds: {
      default: 'dark',
    },
  },
  tags: ['autodocs'],
  argTypes: {
    helperText: '',
    error: false,
  },
  decorators: decorators,
};
export const Outlined = {
  args: {
    variant: 'outlined',
    name: 'country',
    value: '',
    label: 'modal.registration.country',
    helperText: '',
    error: false,
    handleChange: action('changeHandler'),
    handleBlur: action('handleBlur'),
    countries: userCountries,
  },
};
export const OutlinedError = {
  args: {
    variant: 'outlined',
    name: 'country',
    value: '',
    label: 'modal.registration.country',
    helperText: 'modal.registration.required',
    error: true,
    handleChange: action('changeHandler'),
    handleBlur: action('handleBlur'),
    countries: userCountries,
  },
};
export const Standard = {
  args: {
    variant: 'standard',
    name: 'country',
    value: '',
    label: 'modal.registration.country',
    helperText: '',
    error: false,
    handleChange: action('changeHandler'),
    handleBlur: action('handleBlur'),
    countries: userCountries,
  },
};
export const StandardError = {
  args: {
    variant: 'standard',
    name: 'country',
    value: '',
    label: 'modal.registration.country',
    helperText: 'modal.registration.required',
    error: true,
    handleChange: action('changeHandler'),
    handleBlur: action('handleBlur'),
    countries: userCountries,
  },
};
export const Filled = {
  args: {
    variant: 'filled',
    name: 'country',
    value: '',
    label: 'modal.registration.country',
    helperText: '',
    error: false,
    handleChange: action('changeHandler'),
    handleBlur: action('handleBlur'),
    countries: userCountries,
  },
};
export const FilledError = {
  args: {
    variant: 'filled',
    name: 'country',
    value: '',
    label: 'modal.registration.country',
    helperText: 'modal.registration.required',
    error: true,
    handleChange: action('changeHandler'),
    handleBlur: action('handleBlur'),
    countries: userCountries,
  },
};
