import PreviewVideoPassedInterviewSkeleton from '@components/UI/Skeleton/Pages/interviewSkeleton/PreviewVideoPassedInterviewSkeleton/PreviewVideoPassedInterviewSkeleton';

export default PreviewVideoPassedInterviewSkeleton;
